import EmailJunkieMail
import XCTest
@testable import EmailJunkie

/// Tests for the pure reply-worthiness evaluator (item 17). These heuristics are
/// load-bearing — a false skip silently loses a real reply — so they are
/// exercised exhaustively here with no IMAP involved. The bias is conservative:
/// when in doubt, the message must be `.worthy`.
final class ReplyWorthinessTests: XCTestCase {

    private func evaluate(
        sender: String?,
        headers: MailHeaderFields = MailHeaderFields()
    ) -> ReplyWorthinessVerdict {
        ReplyWorthiness.evaluate(ReplyWorthinessSignals(senderEmail: sender, headers: headers))
    }

    // MARK: - Worthy (conservative default)

    func testPlainPersonalMailIsWorthy() {
        XCTAssertEqual(evaluate(sender: "alice@example.com"), .worthy)
    }

    func testWorthyWhenNoSignalsAtAll() {
        XCTAssertEqual(evaluate(sender: nil), .worthy)
    }

    func testOrdinaryContentTypeIsWorthy() {
        let headers = MailHeaderFields(contentType: "multipart/alternative; boundary=abc")
        XCTAssertEqual(evaluate(sender: "bob@example.com", headers: headers), .worthy)
    }

    func testAutoSubmittedNoIsWorthy() {
        // RFC 3834: `no` explicitly means not automated.
        let headers = MailHeaderFields(autoSubmitted: "no")
        XCTAssertEqual(evaluate(sender: "bob@example.com", headers: headers), .worthy)
    }

    func testSenderContainingReplyWordIsNotFalselySkipped() {
        // "reply" alone must not trip the no-reply heuristic.
        XCTAssertEqual(evaluate(sender: "reply-team@example.com"), .worthy)
        XCTAssertEqual(evaluate(sender: "andrew@example.com"), .worthy)
    }

    // MARK: - No-reply senders

    func testNoReplySenderVariantsAreSkipped() {
        for address in [
            "no-reply@example.com",
            "noreply@example.com",
            "donotreply@example.com",
            "do-not-reply@example.com",
            "No_Reply@Example.com",
            "notifications@github.com",
            "mailer-daemon@example.com",
            "postmaster@example.com",
            "bounces+tag@example.com",
            "github-noreply@example.com"
        ] {
            XCTAssertEqual(
                evaluate(sender: address),
                .skip(.noReplySender),
                "expected \(address) to be a no-reply sender"
            )
        }
    }

    func testNoReplyDomainDoesNotTriggerOnLocalPart() {
        // The domain containing "noreply" must not skip a real local part.
        XCTAssertEqual(evaluate(sender: "alice@noreply-mailer.example.com"), .worthy)
    }

    // MARK: - Bulk / list mail

    func testListIdIsSkipped() {
        let headers = MailHeaderFields(listID: "Widgets <widgets.example.com>")
        XCTAssertEqual(evaluate(sender: "news@example.com", headers: headers), .skip(.bulkOrListMail))
    }

    func testListUnsubscribeIsSkipped() {
        let headers = MailHeaderFields(listUnsubscribe: "<mailto:unsub@example.com>")
        XCTAssertEqual(evaluate(sender: "news@example.com", headers: headers), .skip(.bulkOrListMail))
    }

    func testPrecedenceBulkListJunkAreSkipped() {
        for value in ["bulk", "list", "junk", "Bulk", "  LIST  "] {
            let headers = MailHeaderFields(precedence: value)
            XCTAssertEqual(
                evaluate(sender: "news@example.com", headers: headers),
                .skip(.bulkOrListMail),
                "expected precedence \(value) to be bulk/list mail"
            )
        }
    }

    func testPrecedenceFirstClassIsWorthy() {
        let headers = MailHeaderFields(precedence: "first-class")
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .worthy)
    }

    // MARK: - Automated notifications

    func testAutoSubmittedAutoGeneratedIsSkipped() {
        let headers = MailHeaderFields(autoSubmitted: "auto-generated")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    func testAutoSubmittedWithParametersIsSkipped() {
        let headers = MailHeaderFields(autoSubmitted: "auto-replied; owner")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    func testAutoResponseSuppressIsSkipped() {
        let headers = MailHeaderFields(autoResponseSuppress: "All")
        XCTAssertEqual(evaluate(sender: "alerts@example.com", headers: headers), .skip(.automatedNotification))
    }

    // MARK: - Calendar invites

    func testCalendarContentTypeIsSkipped() {
        let headers = MailHeaderFields(contentType: "text/calendar; method=REQUEST; charset=UTF-8")
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .skip(.calendarInvite))
    }

    func testCalendarInviteBeatsAutomationSignals() {
        // A calendar invite from a real person is a calendar invite first.
        let headers = MailHeaderFields(
            autoSubmitted: "auto-generated",
            contentType: "text/calendar; method=REQUEST"
        )
        XCTAssertEqual(evaluate(sender: "alice@example.com", headers: headers), .skip(.calendarInvite))
    }

    // MARK: - Precedence of reasons

    func testNoReplySenderTakesPrecedenceOverListHeaders() {
        let headers = MailHeaderFields(listUnsubscribe: "<mailto:unsub@example.com>")
        XCTAssertEqual(evaluate(sender: "no-reply@example.com", headers: headers), .skip(.noReplySender))
    }
}
